version: '3'
services:
  movies:
    image: abbujio/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: abbujio/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: abbujio/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image:  abbujio/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
